// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: camera.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countCameras = `-- name: CountCameras :one
SELECT COUNT(*)
FROM camera
`

func (q *Queries) CountCameras(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCameras)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCamera = `-- name: CreateCamera :one
INSERT INTO camera (
    camera_name,
    installed_at,
    status,
    url,
    sub_url,
    type
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING camera_id, camera_name, installed_at, status, url, sub_url, type
`

type CreateCameraParams struct {
	CameraName  string         `json:"camera_name"`
	InstalledAt time.Time      `json:"installed_at"`
	Status      string         `json:"status"`
	Url         string         `json:"url"`
	SubUrl      sql.NullString `json:"sub_url"`
	Type        string         `json:"type"`
}

func (q *Queries) CreateCamera(ctx context.Context, arg CreateCameraParams) (Camera, error) {
	row := q.db.QueryRowContext(ctx, createCamera,
		arg.CameraName,
		arg.InstalledAt,
		arg.Status,
		arg.Url,
		arg.SubUrl,
		arg.Type,
	)
	var i Camera
	err := row.Scan(
		&i.CameraID,
		&i.CameraName,
		&i.InstalledAt,
		&i.Status,
		&i.Url,
		&i.SubUrl,
		&i.Type,
	)
	return i, err
}

const deleteCamera = `-- name: DeleteCamera :exec
DELETE FROM camera
WHERE camera_id = ?
`

func (q *Queries) DeleteCamera(ctx context.Context, cameraID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCamera, cameraID)
	return err
}

const getCamera = `-- name: GetCamera :one
SELECT camera_id, camera_name, installed_at, status, url, sub_url, type
FROM camera
WHERE camera_id = ?
LIMIT 1
`

func (q *Queries) GetCamera(ctx context.Context, cameraID int64) (Camera, error) {
	row := q.db.QueryRowContext(ctx, getCamera, cameraID)
	var i Camera
	err := row.Scan(
		&i.CameraID,
		&i.CameraName,
		&i.InstalledAt,
		&i.Status,
		&i.Url,
		&i.SubUrl,
		&i.Type,
	)
	return i, err
}

const listCameras = `-- name: ListCameras :many
SELECT camera_id, camera_name, installed_at, status, url, sub_url, type
FROM camera
ORDER BY camera_id
`

func (q *Queries) ListCameras(ctx context.Context) ([]Camera, error) {
	rows, err := q.db.QueryContext(ctx, listCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.CameraID,
			&i.CameraName,
			&i.InstalledAt,
			&i.Status,
			&i.Url,
			&i.SubUrl,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnlineCameras = `-- name: ListOnlineCameras :many
SELECT camera_id, camera_name, installed_at, status, url, sub_url, type
FROM camera
WHERE status = 'Online'
ORDER BY camera_name
`

func (q *Queries) ListOnlineCameras(ctx context.Context) ([]Camera, error) {
	rows, err := q.db.QueryContext(ctx, listOnlineCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.CameraID,
			&i.CameraName,
			&i.InstalledAt,
			&i.Status,
			&i.Url,
			&i.SubUrl,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamera = `-- name: UpdateCamera :one
UPDATE camera
SET
    camera_name = ?,
    url = ?,
    sub_url = ?,
    type = ?
WHERE camera_id = ?
RETURNING camera_id, camera_name, installed_at, status, url, sub_url, type
`

type UpdateCameraParams struct {
	CameraName string         `json:"camera_name"`
	Url        string         `json:"url"`
	SubUrl     sql.NullString `json:"sub_url"`
	Type       string         `json:"type"`
	CameraID   int64          `json:"camera_id"`
}

func (q *Queries) UpdateCamera(ctx context.Context, arg UpdateCameraParams) (Camera, error) {
	row := q.db.QueryRowContext(ctx, updateCamera,
		arg.CameraName,
		arg.Url,
		arg.SubUrl,
		arg.Type,
		arg.CameraID,
	)
	var i Camera
	err := row.Scan(
		&i.CameraID,
		&i.CameraName,
		&i.InstalledAt,
		&i.Status,
		&i.Url,
		&i.SubUrl,
		&i.Type,
	)
	return i, err
}

const updateCameraStatus = `-- name: UpdateCameraStatus :one
UPDATE camera
SET status = ?
WHERE camera_id = ?
RETURNING camera_id, camera_name, installed_at, status, url, sub_url, type
`

type UpdateCameraStatusParams struct {
	Status   string `json:"status"`
	CameraID int64  `json:"camera_id"`
}

func (q *Queries) UpdateCameraStatus(ctx context.Context, arg UpdateCameraStatusParams) (Camera, error) {
	row := q.db.QueryRowContext(ctx, updateCameraStatus, arg.Status, arg.CameraID)
	var i Camera
	err := row.Scan(
		&i.CameraID,
		&i.CameraName,
		&i.InstalledAt,
		&i.Status,
		&i.Url,
		&i.SubUrl,
		&i.Type,
	)
	return i, err
}
