// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Camera struct {
	CameraID    int64          `json:"camera_id"`
	CameraName  string         `json:"camera_name"`
	InstalledAt time.Time      `json:"installed_at"`
	Status      string         `json:"status"`
	Url         string         `json:"url"`
	SubUrl      sql.NullString `json:"sub_url"`
	Type        string         `json:"type"`
}

type Recording struct {
	RecordID   int64     `json:"record_id"`
	FromCamera int64     `json:"from_camera"`
	FileName   string    `json:"file_name"`
	StartedAt  time.Time `json:"started_at"`
	Duration   int64     `json:"duration"`
}
