// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CountCameras(ctx context.Context) (int64, error)
	CreateCamera(ctx context.Context, arg CreateCameraParams) (Camera, error)
	CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error)
	DeleteCamera(ctx context.Context, cameraID int64) error
	DeleteRecording(ctx context.Context, recordID int64) error
	GetCamera(ctx context.Context, cameraID int64) (Camera, error)
	GetRecordingByID(ctx context.Context, recordID int64) (Recording, error)
	GetRecordingFor(ctx context.Context, arg GetRecordingForParams) ([]Recording, error)
	ListCameras(ctx context.Context) ([]Camera, error)
	ListOnlineCameras(ctx context.Context) ([]Camera, error)
	ListRecordings(ctx context.Context) ([]Recording, error)
	SetEndTime(ctx context.Context, arg SetEndTimeParams) (Recording, error)
	UpdateCamera(ctx context.Context, arg UpdateCameraParams) (Camera, error)
	UpdateCameraStatus(ctx context.Context, arg UpdateCameraStatusParams) (Camera, error)
}

var _ Querier = (*Queries)(nil)
