// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recording.sql

package database

import (
	"context"
	"time"
)

const createRecording = `-- name: CreateRecording :one
INSERT INTO recording (
    from_camera,
    file_name,
    started_at,
    duration
)
VALUES (?, ?, ?, ?)
RETURNING record_id, from_camera, file_name, started_at, duration
`

type CreateRecordingParams struct {
	FromCamera int64     `json:"from_camera"`
	FileName   string    `json:"file_name"`
	StartedAt  time.Time `json:"started_at"`
	Duration   int64     `json:"duration"`
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, createRecording,
		arg.FromCamera,
		arg.FileName,
		arg.StartedAt,
		arg.Duration,
	)
	var i Recording
	err := row.Scan(
		&i.RecordID,
		&i.FromCamera,
		&i.FileName,
		&i.StartedAt,
		&i.Duration,
	)
	return i, err
}

const deleteRecording = `-- name: DeleteRecording :exec
DELETE FROM recording WHERE record_id = ?
`

func (q *Queries) DeleteRecording(ctx context.Context, recordID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecording, recordID)
	return err
}

const listRecordings = `-- name: ListRecordings :many
SELECT record_id, from_camera, file_name, started_at, duration FROM recording ORDER BY started_at
`

func (q *Queries) ListRecordings(ctx context.Context) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, listRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.RecordID,
			&i.FromCamera,
			&i.FileName,
			&i.StartedAt,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDuration = `-- name: SetDuration :one
UPDATE recording
SET duration = ?
WHERE record_id = ?
RETURNING record_id, from_camera, file_name, started_at, duration
`

type SetDurationParams struct {
	Duration int64 `json:"duration"`
	RecordID int64 `json:"record_id"`
}

func (q *Queries) SetDuration(ctx context.Context, arg SetDurationParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, setDuration, arg.Duration, arg.RecordID)
	var i Recording
	err := row.Scan(
		&i.RecordID,
		&i.FromCamera,
		&i.FileName,
		&i.StartedAt,
		&i.Duration,
	)
	return i, err
}
