// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recording.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createRecording = `-- name: CreateRecording :one
INSERT INTO recording (
    from_camera,
    file_name,
    started_at,
    status
)
VALUES (?, ?, ?, ?)
RETURNING record_id, from_camera, file_name, started_at, ended_at, status
`

type CreateRecordingParams struct {
	FromCamera int64     `json:"from_camera"`
	FileName   string    `json:"file_name"`
	StartedAt  time.Time `json:"started_at"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, createRecording,
		arg.FromCamera,
		arg.FileName,
		arg.StartedAt,
		arg.Status,
	)
	var i Recording
	err := row.Scan(
		&i.RecordID,
		&i.FromCamera,
		&i.FileName,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const deleteRecording = `-- name: DeleteRecording :exec
DELETE FROM recording
WHERE record_id = ?
`

func (q *Queries) DeleteRecording(ctx context.Context, recordID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecording, recordID)
	return err
}

const getRecordingByID = `-- name: GetRecordingByID :one
SELECT record_id, from_camera, file_name, started_at, ended_at, status
FROM recording
WHERE record_id = ?
`

func (q *Queries) GetRecordingByID(ctx context.Context, recordID int64) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getRecordingByID, recordID)
	var i Recording
	err := row.Scan(
		&i.RecordID,
		&i.FromCamera,
		&i.FileName,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const getRecordingFor = `-- name: GetRecordingFor :many
SELECT record_id, from_camera, file_name, started_at, ended_at, status
FROM recording
WHERE from_camera = ?
  AND started_at < ?
  AND (ended_at IS NULL OR ended_at >= ?)
ORDER BY started_at ASC
`

type GetRecordingForParams struct {
	FromCamera int64        `json:"from_camera"`
	StartedAt  time.Time    `json:"started_at"`
	EndedAt    sql.NullTime `json:"ended_at"`
}

func (q *Queries) GetRecordingFor(ctx context.Context, arg GetRecordingForParams) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, getRecordingFor, arg.FromCamera, arg.StartedAt, arg.EndedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.RecordID,
			&i.FromCamera,
			&i.FileName,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordings = `-- name: ListRecordings :many
SELECT record_id, from_camera, file_name, started_at, ended_at, status
FROM recording
ORDER BY started_at ASC
`

func (q *Queries) ListRecordings(ctx context.Context) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, listRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.RecordID,
			&i.FromCamera,
			&i.FileName,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEndTime = `-- name: SetEndTime :one
UPDATE recording
SET ended_at = ?
WHERE record_id = ?
RETURNING record_id, from_camera, file_name, started_at, ended_at, status
`

type SetEndTimeParams struct {
	EndedAt  sql.NullTime `json:"ended_at"`
	RecordID int64        `json:"record_id"`
}

func (q *Queries) SetEndTime(ctx context.Context, arg SetEndTimeParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, setEndTime, arg.EndedAt, arg.RecordID)
	var i Recording
	err := row.Scan(
		&i.RecordID,
		&i.FromCamera,
		&i.FileName,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const setStatus = `-- name: SetStatus :one
UPDATE recording
SET status = ?
WHERE record_id = ?
RETURNING record_id, from_camera, file_name, started_at, ended_at, status
`

type SetStatusParams struct {
	Status   string `json:"status"`
	RecordID int64  `json:"record_id"`
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, setStatus, arg.Status, arg.RecordID)
	var i Recording
	err := row.Scan(
		&i.RecordID,
		&i.FromCamera,
		&i.FileName,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}
