// Code generated by govalid; DO NOT EDIT.
package domains

import (
	"context"
	"errors"

	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*RepoCreateCameraOpts)(nil)

	// ErrNilRepoCreateCameraOpts is returned when the RepoCreateCameraOpts is nil.
	ErrNilRepoCreateCameraOpts = errors.New("input RepoCreateCameraOpts is nil")

	// ErrRepoCreateCameraOptsURLRequiredValidation is returned when the URL is required but not provided.
	ErrRepoCreateCameraOptsURLRequiredValidation = govaliderrors.ValidationError{Reason: "field URL is required", Path: "RepoCreateCameraOpts.URL", Type: "required"}

	// ErrRepoCreateCameraOptsURLURLValidation is the error returned when the field is not a valid URL.
	ErrRepoCreateCameraOptsURLURLValidation = govaliderrors.ValidationError{Reason: "field URL must be a valid URL", Path: "RepoCreateCameraOpts.URL", Type: "url"}

	// ErrRepoCreateCameraOptsSURLURLValidation is the error returned when the field is not a valid URL.
	ErrRepoCreateCameraOptsSURLURLValidation = govaliderrors.ValidationError{Reason: "field SURL must be a valid URL", Path: "RepoCreateCameraOpts.SURL", Type: "url"}

	// ErrRepoCreateCameraOptsTypeEnumValidation is the error returned when the value is not in the allowed enum values Generic.
	ErrRepoCreateCameraOptsTypeEnumValidation = govaliderrors.ValidationError{Reason: "field Type must be one of Generic", Path: "RepoCreateCameraOpts.Type", Type: "enum"}

	// ErrRepoCreateCameraOptsTypeRequiredValidation is returned when the Type is required but not provided.
	ErrRepoCreateCameraOptsTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field Type is required", Path: "RepoCreateCameraOpts.Type", Type: "required"}

	// ErrRepoCreateCameraOptsCameraNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrRepoCreateCameraOptsCameraNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field CameraName must have a maximum length of 100", Path: "RepoCreateCameraOpts.CameraName", Type: "maxlength"}

	// ErrRepoCreateCameraOptsCameraNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 3.
	ErrRepoCreateCameraOptsCameraNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field CameraName must have a minimum length of 3", Path: "RepoCreateCameraOpts.CameraName", Type: "minlength"}

	// ErrRepoCreateCameraOptsCameraNameRequiredValidation is returned when the CameraName is required but not provided.
	ErrRepoCreateCameraOptsCameraNameRequiredValidation = govaliderrors.ValidationError{Reason: "field CameraName is required", Path: "RepoCreateCameraOpts.CameraName", Type: "required"}
)

func ValidateRepoCreateCameraOptsContext(ctx context.Context, t *RepoCreateCameraOpts) error {
	if t == nil {
		return ErrNilRepoCreateCameraOpts
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.URL == "" {
		err := ErrRepoCreateCameraOptsURLRequiredValidation
		err.Value = t.URL
		errs = append(errs, err)
	}

	if !validationhelper.IsValidURL(t.URL) {
		err := ErrRepoCreateCameraOptsURLURLValidation
		err.Value = t.URL
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsValidURL(t.SURL) {
		err := ErrRepoCreateCameraOptsSURLURLValidation
		err.Value = t.SURL
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.Type != "Generic" {
		err := ErrRepoCreateCameraOptsTypeEnumValidation
		err.Value = t.Type
		errs = append(errs, err)
	}

	if t.Type == "" {
		err := ErrRepoCreateCameraOptsTypeRequiredValidation
		err.Value = t.Type
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if utf8.RuneCountInString(t.CameraName) > 100 {
		err := ErrRepoCreateCameraOptsCameraNameMaxLengthValidation
		err.Value = t.CameraName
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.CameraName) < 3 {
		err := ErrRepoCreateCameraOptsCameraNameMinLengthValidation
		err.Value = t.CameraName
		errs = append(errs, err)
	}

	if t.CameraName == "" {
		err := ErrRepoCreateCameraOptsCameraNameRequiredValidation
		err.Value = t.CameraName
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateRepoCreateCameraOpts(t *RepoCreateCameraOpts) error {
	return ValidateRepoCreateCameraOptsContext(context.Background(), t)
}

func (t *RepoCreateCameraOpts) Validate() error {
	return ValidateRepoCreateCameraOpts(t)
}

func (t *RepoCreateCameraOpts) ValidateContext(ctx context.Context) error {
	return ValidateRepoCreateCameraOptsContext(ctx, t)
}
