// Code generated by govalid; DO NOT EDIT.
package domains

import (
	"context"
	"errors"

	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*UpdateCameraOpts)(nil)

	// ErrNilUpdateCameraOpts is returned when the UpdateCameraOpts is nil.
	ErrNilUpdateCameraOpts = errors.New("input UpdateCameraOpts is nil")

	// ErrUpdateCameraOptsURLURLValidation is the error returned when the field is not a valid URL.
	ErrUpdateCameraOptsURLURLValidation = govaliderrors.ValidationError{Reason: "field URL must be a valid URL", Path: "UpdateCameraOpts.URL", Type: "url"}

	// ErrUpdateCameraOptsSURLURLValidation is the error returned when the field is not a valid URL.
	ErrUpdateCameraOptsSURLURLValidation = govaliderrors.ValidationError{Reason: "field SURL must be a valid URL", Path: "UpdateCameraOpts.SURL", Type: "url"}

	// ErrUpdateCameraOptsTypeEnumValidation is the error returned when the value is not in the allowed enum values Generic.
	ErrUpdateCameraOptsTypeEnumValidation = govaliderrors.ValidationError{Reason: "field Type must be one of Generic", Path: "UpdateCameraOpts.Type", Type: "enum"}

	// ErrUpdateCameraOptsCameraNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrUpdateCameraOptsCameraNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field CameraName must have a maximum length of 100", Path: "UpdateCameraOpts.CameraName", Type: "maxlength"}

	// ErrUpdateCameraOptsCameraNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 3.
	ErrUpdateCameraOptsCameraNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field CameraName must have a minimum length of 3", Path: "UpdateCameraOpts.CameraName", Type: "minlength"}

	// ErrUpdateCameraOptsCameraIdRequiredValidation is returned when the CameraId is required but not provided.
	ErrUpdateCameraOptsCameraIdRequiredValidation = govaliderrors.ValidationError{Reason: "field CameraId is required", Path: "UpdateCameraOpts.CameraId", Type: "required"}
)

func ValidateUpdateCameraOptsContext(ctx context.Context, t *UpdateCameraOpts) error {
	if t == nil {
		return ErrNilUpdateCameraOpts
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsValidURL(t.URL) {
		err := ErrUpdateCameraOptsURLURLValidation
		err.Value = t.URL
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsValidURL(t.SURL) {
		err := ErrUpdateCameraOptsSURLURLValidation
		err.Value = t.SURL
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.Type != "Generic" {
		err := ErrUpdateCameraOptsTypeEnumValidation
		err.Value = t.Type
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if utf8.RuneCountInString(t.CameraName) > 100 {
		err := ErrUpdateCameraOptsCameraNameMaxLengthValidation
		err.Value = t.CameraName
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.CameraName) < 3 {
		err := ErrUpdateCameraOptsCameraNameMinLengthValidation
		err.Value = t.CameraName
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.CameraId == 0 {
		err := ErrUpdateCameraOptsCameraIdRequiredValidation
		err.Value = t.CameraId
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateUpdateCameraOpts(t *UpdateCameraOpts) error {
	return ValidateUpdateCameraOptsContext(context.Background(), t)
}

func (t *UpdateCameraOpts) Validate() error {
	return ValidateUpdateCameraOpts(t)
}

func (t *UpdateCameraOpts) ValidateContext(ctx context.Context) error {
	return ValidateUpdateCameraOptsContext(ctx, t)
}
