// Code generated by govalid; DO NOT EDIT.
package domains

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*CreateRecordingOpts)(nil)

	// ErrNilCreateRecordingOpts is returned when the CreateRecordingOpts is nil.
	ErrNilCreateRecordingOpts = errors.New("input CreateRecordingOpts is nil")

	// ErrCreateRecordingOptsFromCameraRequiredValidation is returned when the FromCamera is required but not provided.
	ErrCreateRecordingOptsFromCameraRequiredValidation = govaliderrors.ValidationError{Reason: "field FromCamera is required", Path: "CreateRecordingOpts.FromCamera", Type: "required"}

	// ErrCreateRecordingOptsFileNameRequiredValidation is returned when the FileName is required but not provided.
	ErrCreateRecordingOptsFileNameRequiredValidation = govaliderrors.ValidationError{Reason: "field FileName is required", Path: "CreateRecordingOpts.FileName", Type: "required"}
)

func ValidateCreateRecordingOptsContext(ctx context.Context, t *CreateRecordingOpts) error {
	if t == nil {
		return ErrNilCreateRecordingOpts
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.FromCamera == 0 {
		err := ErrCreateRecordingOptsFromCameraRequiredValidation
		err.Value = t.FromCamera
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.FileName == "" {
		err := ErrCreateRecordingOptsFileNameRequiredValidation
		err.Value = t.FileName
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateCreateRecordingOpts(t *CreateRecordingOpts) error {
	return ValidateCreateRecordingOptsContext(context.Background(), t)
}

func (t *CreateRecordingOpts) Validate() error {
	return ValidateCreateRecordingOpts(t)
}

func (t *CreateRecordingOpts) ValidateContext(ctx context.Context) error {
	return ValidateCreateRecordingOptsContext(ctx, t)
}
